[book]
description = "Book to guide developers in their Rust learning"
authors = ["Eduardo Canellas de Oliveira"]
language = "en"
multilingual = false
src = "src"

[rust]
edition = "2021"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/dbofmmbt/rust-handbook"

[output.html.playground]
editable = true
