[book]
description = "Guia para orientar pessoas desenvolvedoras no aprendizado de Rust"
authors = ["Eduardo Canellas de Oliveira"]
language = "pt-br"
multilingual = false
src = "src"

[rust]
edition = "2021"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/dbofmmbt/guia-para-entender-rust"

[output.html.playground]
editable = true
